//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.SendEmail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.SendEmail.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;display:inline-block;margin:auto&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;center&quot; bgcolor=&quot;##BackgroundColor##&quot;
        ///            style=&quot;padding:24px; -webkit-border-radius: 6px; -moz-border-radius: 6px; border: 1px solid ##BorderColor##; border-radius: 6px; color: ##TextColor##; display: block;background-color:##BackgroundColor##&quot;&gt;
        ///            &lt;table&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td&gt;##Description##&lt;/td&gt;
        ///                    &lt;/tr&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardTemplate {
            get {
                return ResourceManager.GetString("CardTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;style&gt;
        ///		/* Remove space around the email design. */
        ///		html,
        ///		body {
        ///			margin: 0 auto !important;
        ///			padding: 0 !important;
        ///			height: 100% !important;
        ///			width: 100% !important;
        ///		}
        ///
        ///		/* Stop Outlook resizing small text. */
        ///		* {
        ///			-ms-text-size-adjust: 100%;
        ///		}
        ///
        ///		/* Stop Outlook from adding extra spacing to tables. */
        ///		table, tr, td {
        ///			border-spacing: 0 !important;
        ///			mso-table-lspace: 0px !important;
        ///			mso-table-rs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailBaseTemplate {
            get {
                return ResourceManager.GetString("EmailBaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;display:inline-block;margin:auto&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;center&quot; bgcolor=&quot;##BackgroundColor##&quot;
        ///            style=&quot;padding:24px; -webkit-border-radius: 6px; -moz-border-radius: 6px; border: 1px solid ##BorderColor##; border-radius: 6px; color: ##TextColor##; display: block;background-color:##BackgroundColor##&quot;&gt;
        ///            &lt;table&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td&gt;##Description##&lt;/td&gt;
        ///                    &lt;/tr&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeaderTemplate {
            get {
                return ResourceManager.GetString("HeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;display: inline-block; margin: auto; margin-top: ##MarginTop##px;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///            &lt;!--[if mso]&gt;
        ///    &lt;v:roundrect xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///                 xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///                 href=&quot;##Link##&quot;
        ///                 style=&quot;width: ##LinkWidth##px;height: ##LinkHeight##px;v-text-anchor:middle;&quot; arcsize=&quot;##BorderRadiusMSO##%&quot;
        ///                 stroke=&quot;f&quot; fillcolor=&quot;##BackgroundColor##&quot;&gt;
        ///        &lt;w:anchorlock/&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoundedBtnTemplate {
            get {
                return ResourceManager.GetString("RoundedBtnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--[if mso]&gt;
        ///&lt;v:roundrect xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///             xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///             style=&quot;height: ##UserAvatarSize##px; width: ##UserAvatarSize##px;v-text-anchor:middle;&quot; arcsize=&quot;50%&quot;
        ///             stroke=&quot;f&quot; fillcolor=&quot;##AvatarColor##&quot;&gt;
        ///    &lt;w:anchorlock/&gt;
        ///    &lt;v:textbox inset=&quot;0,0,0,0&quot;&gt;
        ///        &lt;center style=&quot;display:inline-block;&quot;&gt;
        ///            &lt;a href=&quot;##UserUrl##&quot; style=&quot;color:#000000;font-family:sans-serif;font-size:##UserAvatarFontSize# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAvatarLettersTemplate {
            get {
                return ResourceManager.GetString("UserAvatarLettersTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; style=&quot;display: inline-block; vertical-align: middle&quot;&gt;
        ///    &lt;tr style=&quot;text-align: center&quot;&gt;
        ///        &lt;td style=&quot;display:block;height: ##UserAvatarSize##px;&quot;&gt;
        ///            &lt;a href=&quot;##UserUrl##&quot;&gt;&lt;img style=&quot;border-radius:50%;height:##UserAvatarSize##px; width: ##UserAvatarSize##px; min-height: ##UserAvatarSize##px; min-width: ##UserAvatarSize##px;object-fit:cover&quot; height=&quot;##UserAvatarSize##&quot; width=&quot;##UserAvatarSize##&quot; src=&quot;cid:##UserIconId##&quot;&gt;&lt;/a&gt;
        ///        &lt;/td&gt;
        ///    &lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAvatarTemplate {
            get {
                return ResourceManager.GetString("UserAvatarTemplate", resourceCulture);
            }
        }
    }
}
